spring:
  application:
    name: dad-marketplace
  r2dbc:
    url: r2dbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            client-name: Discord
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: ${BASE_URL}/login/oauth2/code/${REGISTRATION_ID}
            scope: identify, email
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id
