# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dad-marketplace:latest
    container_name: dad-marketplace-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - BASE_URL=${BASE_URL:-http://localhost:8080}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dad-marketplace-network
    restart: unless-stopped
    volumes:
      - app-logs:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mysql:
    image: mysql:8.0
    container_name: dad-marketplace-mysql
    environment:
      # 환경변수 사용 (기본값 포함)
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      # 스키마 파일을 MySQL 초기화 디렉토리에 마운트
      - ./src/main/resources/schema:/docker-entrypoint-initdb.d
      # 데이터 영속성을 위한 볼륨 (선택사항)
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    networks:
      - dad-marketplace-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

networks:
  dad-marketplace-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  app-logs:
    driver: local
