version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: highroller-market-mysql
    environment:
      # 환경변수 사용 (기본값 포함)
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      # 스키마 파일을 MySQL 초기화 디렉토리에 마운트
      - ./src/main/resources/schema:/docker-entrypoint-initdb.d
      # 데이터 영속성을 위한 볼륨 (선택사항)
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
